/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;

import com.gvillena.MainForm;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author ASUS
 */
public class Modulo_de_Pago extends javax.swing.JFrame {
    
    String ttarjeta = "";
    String dfecha = "";
    String mfecha = "";
    
    String titular="",tarjeta="",codseguridad="",caducidad="",precio="";
   BufferedWriter bw ;
    PrintWriter pw;
    FileWriter fw;
    File f; 
    
    JSONObject obj = new JSONObject();
    JSONArray list = new JSONArray();
    
    private String cadena;

    /**
     * Creates new form Modulo_de_Pago
     */
    public Modulo_de_Pago() {
        this.cadena = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLTiendaClaro = new javax.swing.JLabel();
        jPDatos = new javax.swing.JPanel();
        jLTipoTarjeta = new javax.swing.JLabel();
        jBTTarjeta = new javax.swing.JComboBox();
        jLNumeroTarjeta = new javax.swing.JLabel();
        jTFNumeroTarjeta = new javax.swing.JTextField();
        jLCodigoSeguridad = new javax.swing.JLabel();
        jTFCodigoSeguridad = new javax.swing.JTextField();
        jLFechaCaducidad = new javax.swing.JLabel();
        jCBFechaCaducidad1 = new javax.swing.JComboBox();
        jCBFechaCaducidad2 = new javax.swing.JComboBox();
        jLImporteTotal = new javax.swing.JLabel();
        jTFImporteTotal = new javax.swing.JTextField();
        jLDsipositivo = new javax.swing.JLabel();
        jTFEquipo = new javax.swing.JTextField();
        jLPlan = new javax.swing.JLabel();
        jTFPlan = new javax.swing.JTextField();
        jPComprar = new javax.swing.JPanel();
        jBComprarFinal = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jRBTerminosyCondiciones = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTiendaClaro.setFont(new java.awt.Font("Bodoni MT", 1, 40)); // NOI18N
        jLTiendaClaro.setText(" CLARO CHOSICA");

        jLTipoTarjeta.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLTipoTarjeta.setText("Tipo de Tarjeta");
        jLTipoTarjeta.setPreferredSize(new java.awt.Dimension(120, 25));

        jBTTarjeta.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jBTTarjeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Diners Club", "Master Card", "American Express", " " }));
        jBTTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBTTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTTarjetaActionPerformed(evt);
            }
        });

        jLNumeroTarjeta.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLNumeroTarjeta.setText("Numero de Tarjeta");
        jLNumeroTarjeta.setPreferredSize(new java.awt.Dimension(25, 120));

        jTFNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroTarjetaActionPerformed(evt);
            }
        });

        jLCodigoSeguridad.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLCodigoSeguridad.setText("Codigo de Seguridad");
        jLCodigoSeguridad.setPreferredSize(new java.awt.Dimension(120, 25));

        jLFechaCaducidad.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLFechaCaducidad.setText("Fecha de Caducidad");

        jCBFechaCaducidad1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCBFechaCaducidad2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        jCBFechaCaducidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFechaCaducidad2ActionPerformed(evt);
            }
        });

        jLImporteTotal.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLImporteTotal.setText("Importe Total");

        jTFImporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFImporteTotalActionPerformed(evt);
            }
        });

        jLDsipositivo.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLDsipositivo.setText("Dispositivo");

        jLPlan.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLPlan.setText("Plan de Compra");

        javax.swing.GroupLayout jPDatosLayout = new javax.swing.GroupLayout(jPDatos);
        jPDatos.setLayout(jPDatosLayout);
        jPDatosLayout.setHorizontalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosLayout.createSequentialGroup()
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosLayout.createSequentialGroup()
                        .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLPlan))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosLayout.createSequentialGroup()
                                .addContainerGap(29, Short.MAX_VALUE)
                                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLTipoTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLNumeroTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLCodigoSeguridad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLFechaCaducidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPDatosLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLDsipositivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPDatosLayout.createSequentialGroup()
                        .addComponent(jCBFechaCaducidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBFechaCaducidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBTTarjeta, 0, 200, Short.MAX_VALUE)
                    .addComponent(jTFNumeroTarjeta)
                    .addComponent(jTFEquipo)
                    .addComponent(jTFPlan)
                    .addComponent(jTFImporteTotal))
                .addGap(62, 62, 62))
        );
        jPDatosLayout.setVerticalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBFechaCaducidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBFechaCaducidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDsipositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jBTTarjeta.getAccessibleContext().setAccessibleName("");

        jBComprarFinal.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jBComprarFinal.setText("! COMPRAR !");
        jBComprarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComprarFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPComprarLayout = new javax.swing.GroupLayout(jPComprar);
        jPComprar.setLayout(jPComprarLayout);
        jPComprarLayout.setHorizontalGroup(
            jPComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPComprarLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jBComprarFinal)
                .addGap(25, 25, 25))
        );
        jPComprarLayout.setVerticalGroup(
            jPComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPComprarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jBComprarFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jBAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        jRBTerminosyCondiciones.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jRBTerminosyCondiciones.setText("Acepto Terminos y Condiciones");
        jRBTerminosyCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTerminosyCondicionesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\tarjetas.png")); // NOI18N
        jLabel1.setText("Tarjetas Disponibles:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seo3-23-64.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lock_1.png"))); // NOI18N
        jLabel3.setText("IMFORMACION SEGURA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTiendaClaro)
                        .addGap(538, 538, 538)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAtras)
                                .addGap(126, 126, 126)
                                .addComponent(jRBTerminosyCondiciones))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(jLabel3)))))
                        .addGap(34, 34, 34)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTiendaClaro)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBTerminosyCondiciones)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBAtras))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBTerminosyCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTerminosyCondicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBTerminosyCondicionesActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
        MainForm main = new MainForm();
        main. setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jBComprarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComprarFinalActionPerformed
       
        
        
        try {
            guargarVenta();
            JOptionPane.showMessageDialog(null," SE REALIZO LA COMPRA EXITOSAMENTE ");
           
            
                   
          
        } catch (IOException ex) {
              
          }
       

        
    }//GEN-LAST:event_jBComprarFinalActionPerformed

    private void jCBFechaCaducidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFechaCaducidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBFechaCaducidad2ActionPerformed

    private void jTFNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroTarjetaActionPerformed

    private void jBTTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTTarjetaActionPerformed

    private void jTFImporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFImporteTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFImporteTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo_de_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo_de_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo_de_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo_de_Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo_de_Pago().setVisible(true);
            }
        });
    }
    
    public void guargarVenta()throws IOException{
        ttarjeta=jBTTarjeta.getSelectedItem().toString();
        dfecha = jCBFechaCaducidad1.getSelectedItem().toString();
        mfecha=jCBFechaCaducidad1.getSelectedItem().toString();
        
        
     f= new File("C:\\Users\\ASUS\\Documents\\json:\\RegistroDVentas.txt");  
      obj.put("","Caja Amante Marco");
      obj.put("","");
      obj.put("TIENDA", "CLARO");
      JSONObject objc = new JSONObject();
      obj.put("FACTURA",objc );
      objc.put("Dispositivo ", jTFEquipo.getText());
      objc.put("Plan ", jTFPlan.getText());
      objc.put("Importe ", jTFImporteTotal.getText());
      objc.put("Tipo de Tarjeta ", ttarjeta);
      objc.put("Numero de Tarjeta ", jTFNumeroTarjeta.getText());
      objc.put("Cod. Tarjeta",jTFCodigoSeguridad.getText());
      objc.put("Fecha de Caducidad de Tarjeta", dfecha+"/"+mfecha);
      
      fw= new FileWriter("C:\\Users\\ASUS\\Documents\\json\\RegistroDVentas.txt");
      fw.write(obj.toJSONString());
      fw.flush();
      fw.close();
    }

    
    /*public void guardasVenta(){
        try{
            FileWrite fw = new FileWrite("Venta.txt",true);
            BufferedWrite
            
        }catch(Exception e){
    }*/
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBComprarFinal;
    private javax.swing.JComboBox jBTTarjeta;
    private javax.swing.JComboBox jCBFechaCaducidad1;
    private javax.swing.JComboBox jCBFechaCaducidad2;
    private javax.swing.JLabel jLCodigoSeguridad;
    private javax.swing.JLabel jLDsipositivo;
    private javax.swing.JLabel jLFechaCaducidad;
    private javax.swing.JLabel jLImporteTotal;
    private javax.swing.JLabel jLNumeroTarjeta;
    private javax.swing.JLabel jLPlan;
    private javax.swing.JLabel jLTiendaClaro;
    private javax.swing.JLabel jLTipoTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPComprar;
    private javax.swing.JPanel jPDatos;
    private javax.swing.JRadioButton jRBTerminosyCondiciones;
    private javax.swing.JTextField jTFCodigoSeguridad;
    public static javax.swing.JTextField jTFEquipo;
    public static javax.swing.JTextField jTFImporteTotal;
    private javax.swing.JTextField jTFNumeroTarjeta;
    public static javax.swing.JTextField jTFPlan;
    // End of variables declaration//GEN-END:variables
}
